spring:
  redis:
    host: 3.128.159.68
    port: 6379
    password:
    time-to-live: 30000
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://deltacare:deltacare@cluster0-shard-00-00.nzhz7.mongodb.net:27017,cluster0-shard-00-01.nzhz7.mongodb.net:27017,cluster0-shard-00-02.nzhz7.mongodb.net:27017/deltacare?ssl=true&replicaSet=atlas-w8mek1-shard-0&authSource=admin&retryWrites=true&w=majority
  kafka:
    bootstrap-servers: ec2-3-128-159-68.us-east-2.compute.amazonaws.com:9092
    consumer:
      group-id: painel
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      missing-topics-fatal: false
      ack-mode: manual_immediate
app:
  topic: red